// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDROhjKdkJDdWZqxSXY33_Hbkk1_xWsOhU',
    appId: '1:972053044129:web:6d0ca0329dd816536f09e0',
    messagingSenderId: '972053044129',
    projectId: 'bhoomiseva-cf0ae',
    authDomain: 'bhoomiseva-cf0ae.firebaseapp.com',
    storageBucket: 'bhoomiseva-cf0ae.appspot.com',
    measurementId: 'G-ZSNTQ9PHPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACdwA37yMHfqqpNJnTNWkZG4UOFHb_dh4',
    appId: '1:972053044129:android:ef6580ae79abe58f6f09e0',
    messagingSenderId: '972053044129',
    projectId: 'bhoomiseva-cf0ae',
    storageBucket: 'bhoomiseva-cf0ae.appspot.com',
  );
}
